# Dependencies
#markdown:         redcarpet
markdown:         kramdown # for abbreviations and footnotes
highlighter:	  'rogue'

kramdown:
  input: GFM
  
# Permalinks
permalink:        /posts/:title/

# Setup
title:            'Code is Fun'
tagline:          'Adrian Scipcă''s blog'
description:      'Technical ramblings of a Senior Software Engineer'
url:              https://blog.scene.ro
baseurl:          /

author:
  name:           'Adrian Scipcă'
  url:            https://github.com/benishor

plugins: [jekyll-paginate]
paginate:         5
